method: onet
data:
  path: data/ShapeNet
  img_folder: img_choy2016
  img_size: 224 
  points_subsample: [1024, 1024] 
model:
  encoder_latent: null
  decoder: cbatchnorm
  encoder: resnet18
  c_dim: 256
  z_dim: 0
training:
  out_dir:  out/ablation/sampling_equal
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: -1
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
