# Continuous integration tests executed on push and pull request actions
# see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x

    - name: Install system dependencies
      run: |
        sudo xargs apt-get -y install < requirements.unix
    - name: Linter
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        flake8 --config=.flake8 tensorflow_graphics/
    - name: Build rasterizer
      run: |
        docker run -v ${PWD}:/working_dir -w /working_dir  tensorflow/tensorflow:custom-op-ubuntu16 "./build_rasterizer.sh"
    - name: Install pip requirements
      run: |
        pip install -r requirements.txt
    - name: Test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install pytest coveralls
        coverage run --source tensorflow_graphics -m py.test
        coveralls
    - name: Build and Install
      run: |
        python setup.py sdist bdist_wheel
        pip install dist/tensorflow_graphics*.whl
    - name: Test install
      run: |
        cd $(mktemp -d) && python -c 'import tensorflow_graphics as tfg'
