# Publishes tfg-nightly at https://test.pypi.org/project/tfg-nightly
# See: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Deploy tfg-nightly to pypi

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # runs daily at 00:30 am
    - cron:  '30 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install system dependencies
      run: |
        sudo apt-get -y install libopenexr-dev
        sudo apt-get -y install libgles2-mesa-dev
        sudo apt-get -y install libc-ares-dev
    - name: Install pip requirements
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine pytest
        pip install -r requirements.txt
    - name: Test
      run: |
        pytest tensorflow_graphics
    - name: Build nightly
      run: |
        python setup.py sdist bdist_wheel --nightly
    - name: Install (and test)
      run: |
        pip install dist/*.whl
        cd $(mktemp -d) && python -c 'import tensorflow_graphics as tfg'     
    - name: Publish to pypi (TEST)
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      run: |
        twine upload --repository testpypi dist/*
